name: DIsoN
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=1.3.0=py310h06a4308_0
  - aiohttp=3.8.3=py310h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py310h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py310h06a4308_0
  - attrs=22.1.0=py310h06a4308_0
  - babel=2.11.0=py310h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py310h06a4308_0
  - blosc=1.21.3=h6a678d5_0
  - bottleneck=1.3.5=py310ha9d4c09_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py310h7f8727e_1002
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.7.4=py310h06a4308_0
  - cffi=1.15.1=py310h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - cloudpickle=3.0.0=py310h06a4308_0
  - comm=0.1.2=py310h06a4308_0
  - contourpy=1.0.5=py310hdb19cb5_0
  - cryptography=39.0.1=py310h9ce1e76_2
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cython=3.0.10=py310h5eee18b_0
  - cytoolz=0.12.2=py310h5eee18b_0
  - dask-core=2023.6.0=py310h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - eigen=3.4.0=hdb19cb5_0
  - entrypoints=0.4=py310h06a4308_0
  - exceptiongroup=1.0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py310h5eee18b_0
  - fsspec=2024.3.1=py310h06a4308_0
  - geos=3.8.0=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - grpcio=1.62.2=py310h6a678d5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2021.8.26=py310h46e8fbd_2
  - imageio=2.33.1=py310h06a4308_0
  - imbalanced-learn=0.7.0=py_1
  - imgaug=0.4.0=pyhd3eb1b0_0
  - importlib-metadata=7.0.1=py310h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.19.2=py310h2f386ee_0
  - ipython=8.10.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.1.1=py310h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310h06a4308_0
  - jupyter=1.0.0=py310h06a4308_8
  - jupyter_client=7.4.9=py310h06a4308_0
  - jupyter_console=6.6.2=py310h06a4308_0
  - jupyter_core=5.2.0=py310h06a4308_0
  - jupyter_server=1.23.4=py310h06a4308_0
  - jupyterlab=3.5.3=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py310h06a4308_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.4=py310h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.4=py310h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.2.106=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libfaiss=1.8.0=h5aaf3ed_0_cuda11.4.4
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py310h06a4308_0
  - lxml=5.2.1=py310hdbbb534_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py310h06a4308_0
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib=3.7.0=py310h06a4308_0
  - matplotlib-base=3.7.0=py310h1128e8f_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=0.8.4=py310h7f8727e_1000
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - multidict=6.0.2=py310h5eee18b_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - nbclassic=0.5.2=py310h06a4308_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.5.4=py310h06a4308_0
  - nbformat=5.7.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py310h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - notebook=6.5.2=py310h06a4308_0
  - notebook-shim=0.2.2=py310h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.7=py310h85018f9_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - oauthlib=3.2.1=py310h06a4308_0
  - opencv=4.10.0=py310h0a8ef67_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.14=h5eee18b_0
  - packaging=22.0=py310h06a4308_0
  - pandas=1.5.3=py310h1128e8f_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py310h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py310h5eee18b_0
  - pixman=0.40.0=h7f8727e_1
  - pluggy=1.0.0=py310h06a4308_1
  - ply=3.11=py310h06a4308_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py310h06a4308_0
  - prompt-toolkit=3.0.36=py310h06a4308_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=4.25.3=py310h12ddb61_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py310h06a4308_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=py310h06a4308_0
  - pyqt=5.15.7=py310h6a678d5_1
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - pytest=7.4.0=py310h06a4308_0
  - python=3.10.14=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310h06a4308_0
  - pyzmq=23.2.0=py310h6a678d5_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=hbbf29b9_6
  - qtconsole=5.4.0=py310h06a4308_0
  - qtpy=2.2.0=py310h06a4308_0
  - qtwebkit=5.212=h3fafdc1_5
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py310h06a4308_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.20.0=py310h6a678d5_0
  - scikit-learn=1.0.1=py310h00e6091_0
  - scipy=1.12.0=py310h5f9d8c6_0
  - seaborn=0.12.2=py310h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310h06a4308_0
  - shapely=2.0.5=py310h006c72b_0
  - sip=6.6.2=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.2.0=py310h06a4308_1
  - soupsieve=2.3.2.post1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.11.0=py310h06a4308_0
  - tensorboard-data-server=0.6.1=py310h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - terminado=0.17.1=py310h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - torchaudio=0.13.0=py310_cu117
  - tornado=6.2=py310h5eee18b_0
  - traitlets=5.7.1=py310h06a4308_0
  - tzdata=2022g=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=0.58.0=py310h06a4308_4
  - werkzeug=2.2.2=py310h06a4308_0
  - wheel=0.38.4=py310h06a4308_0
  - widgetsnbextension=3.5.2=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py310h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.17.0=py310h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - antlr4-python3-runtime==4.9.3
    - arch==7.0.0
    - astunparse==1.6.3
    - cfgv==3.4.0
    - deepod==0.4.1
    - deprecated==1.2.18
    - diffdist==0.1
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - einops==0.8.0
    - faiss-gpu==1.7.2
    - filelock==3.13.1
    - flatbuffers==1.12
    - functorch==1.13.1
    - gast==0.4.0
    - gdown==5.2.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-pasta==0.2.0
    - h5py==3.7.0
    - higher==0.2.1
    - huggingface-hub==0.24.5
    - humanize==4.12.2
    - hydra-core==1.3.2
    - identify==2.6.0
    - imagehash==4.3.1
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.1
    - libmr==0.1.9
    - lightning==2.4.0
    - lightning-utilities==0.11.7
    - littleutils==0.2.2
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - monai==1.3.0
    - mpld3==0.5.10
    - mpmath==1.3.0
    - msgpack==1.0.8
    - nfnets-pytorch==0.1.3
    - nibabel==5.1.0
    - nodeenv==1.9.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.20
    - nvidia-nvtx-cu12==12.1.105
    - ogb==1.3.5
    - omegaconf==2.3.0
    - opencv-python==4.10.0.84
    - opt-einsum==3.3.0
    - outdated==0.2.2
    - pathtools==0.1.2
    - patsy==0.5.6
    - pip==22.2.1
    - platformdirs==4.2.2
    - plotly==5.13.1
    - pre-commit==3.8.0
    - promise==2.3
    - psutil==5.9.1
    - pyarrow==17.0.0
    - pygments==2.19.1
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.0
    - pytorch-lightning==2.4.0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - ray==2.6.1
    - rich==14.0.0
    - safetensors==0.4.4
    - sentry-sdk==1.9.5
    - setproctitle==1.3.2
    - shellingham==1.5.4
    - shortuuid==1.0.9
    - simpleitk==2.4.1
    - smmap==5.0.0
    - statsmodels==0.14.2
    - sympy==1.13.2
    - tenacity==8.2.2
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - timm==1.0.8
    - torch==1.13.0
    - torch-geometric==2.5.3
    - torcheval==0.0.7
    - torchio==0.20.6
    - torchmetrics==1.4.3
    - torchvision==0.19.0
    - torchxrayvision==1.2.3
    - tqdm==4.64.1
    - triton==3.0.0
    - typer==0.15.2
    - typing-extensions==4.12.2
    - urllib3==1.26.12
    - virtualenv==20.26.3
    - wandb==0.13.2
    - wilds==2.0.0
    - wrapt==1.14.1
